name: deepfakedetector
dependencies:
- python=3.7
- jupyterlab=0.35.4
- pyviz/label/dev::pyviz=0.10.0
- pyviz/label/dev::hvplot=0.4.0
- pip
- pip:
    - ipynbname
    - tensorflow==2.0.0
    - stingray
    - sklearn
    - jupyter
    - ipython
    - matplotlib
    - nbformat
    - protobuf==3.20.*
